### ISSUE TITLE
License in bower.json

### ISSUE THREAD

**Issue by JosefJezek** [PolymerEl/multi-chart#1]
Please add license to bower.json. I created awesome chart elements collection, this element is missing.

https://beta.webcomponents.org/element/PolymerEl/multi-chart
https://beta.webcomponents.org/collection/StartPolymer/awesome-chart-elements

**Comment by christophe-g** [comment]
Added the licence to bower.json

I am choosing a [BSL licence](http://monty-says.blogspot.fr/2016/08/applying-business-source-licensing-bsl.html) and - as the license is pretty new - not sure it will be recognized as an approved OSI licence yet. 

It is anyway licensed under GPL-2 before the release of version 1.0.0

Cheers,
C.
