### ISSUE TITLE
Polymer 3 and d3v5 support?

### ISSUE THREAD

**Issue by nomego** [PolymerEl/multi-chart#4]
Hi, are you planning on upgrading to Polymer 3 anytime soon?
Also, it seems like you use d3-bundle-element, which in turn seems to use d3v4?

This project seems like a good fit to upgrade to d3v5 and Polymer 3 to make more use of ES modules?

**Comment by christophe-g** [comment]
@nomego  - I am following this thread https://github.com/w3c/webcomponents/issues/645 with a lot of attention and wait for a decisive conclusion before committing to Polymer 3.0 for the main app using this library (multi-chart / multi-verse and multi-geo would follow).

That being said, I agree it would be nice to get rid of the bundle approach  and eventually move to smth like https://github.com/pikapkg/web.

d3-bundle-element now uses d3v5.

**Comment by nomego** [comment]
Oh ok. Since it's a bit in the future, wouldn't it make sense to go to Polymer 3 and then possibly extract the template to an HTML module later on?

Also, since it's not ES modules I assume d3-bundle-element mainly uses bower?
https://github.com/PolymerEl/d3-bundle-element/blob/master/bower.json#L10
